In [ ]:
import numpy as np
import pandas as pd
pd.set_option('display.max_colwidth',200)

In [ ]:
data = pd.read_pickle('/content/drive/MyDrive/Sentiment_analysis_tweets/Data/cleaned_tweets_1.pkl')

In [ ]:
data.head()

id  label  \
0   1      0   
1   2      0   
2   3      0   
3   4      0   
4   5      1   

                                                                                                                                 tweet  \
0     #fingerprint #Pregnancy Test https://goo.gl/h1MfQV #android #apps #beautiful #cute #health #igers #iphoneonly #iphonesia #iphone   
1  Finally a transparant silicon case ^^ Thanks to my uncle :) #yay #Sony #Xperia #S #sonyexperias… http://instagram.com/p/YGEt5JC6JM/   
2          We love this! Would you go? #talk #makememories #unplug #relax #iphone #smartphone #wifi #connect... http://fb.me/6N3LsUpCu   
3                     I'm wired I know I'm George I was made that way ;) #iphone #cute #daventry #home http://instagr.am/p/Li_5_ujS4k/   
4         What amazing service! Apple won't even talk to me about a question I have unless I pay them $19.95 for their stupid support!   

                                                                                                           cleaned_tweets  \
0                         fingerprint pregnancy test android apps beautiful cute health igers iphoneonly iphonesia iphone   
1                                    finally a transparant silicon case thanks to my uncle yay sony xperia s sonyexperias   
2                                 we love this would you go talk makememories unplug relax iphone smartphone wifi connect   
3                                              i am wired i know i am george i wa made that way iphone cute daventry home   
4  what amazing service apple will not even talk to me about a question i have unless i pay them for their stupid support   

                                                                     cleaned_tweets_with_stopwords  
0  fingerprint pregnancy test android apps beautiful cute health igers iphoneonly iphonesia iphone  
1                       finally transparant silicon case thanks uncle yay sony xperia sonyexperias  
2                               love talk makememories unplug relax iphone smartphone wifi connect  
3                                                  wired know george way iphone cute daventry home  
4                                    amazing service apple talk question unless pay stupid support

In [ ]:
tweets_list = list(data['cleaned_tweets'].apply(lambda x: x.split()))

In [ ]:
tweets_list[0]

['fingerprint',
 'pregnancy',
 'test',
 'android',
 'apps',
 'beautiful',
 'cute',
 'health',
 'igers',
 'iphoneonly',
 'iphonesia',
 'iphone']

In [ ]:
from gensim.models import Word2Vec
cbow_model = Word2Vec(tweets_list, vector_size=300, window=3, min_count=5, sg=0)

In [ ]:
cbow_model.wv.index_to_key[:20]

['iphone',
 'apple',
 'i',
 'my',
 'the',
 'to',
 'a',
 'is',
 'samsung',
 'it',
 'and',
 'you',
 'new',
 'twitter',
 'for',
 'com',
 'phone',
 'me',
 'sony',
 'not']

In [ ]:
len(cbow_model.wv.index_to_key)

2421

In [ ]:
def document_vector(doc):
  """ Create document vectors by averaging word vectors. Remove out-of-vocabulary words."""

  doc1 = [word for word in doc.split() if word in cbow_model.wv.index_to_key]

  wv1 = []
  for word in doc1:
    wv1.append(cbow_model.wv.get_vector(word))
  wv1_ = np.array(wv1)
  wv1_mean = wv1_.mean(axis=0)
  return wv1_mean

In [ ]:
m = document_vector(data['cleaned_tweets'][0])


In [ ]:
tweets_temp = data['cleaned_tweets'].apply(document_vector)

In [ ]:
tweets_temp

0       [0.0153355505, 0.2921411, -0.13737473, 0.05652038, 0.010556262, -0.42529294, 0.27298248, 0.6159625, -0.12607321, 0.1443852, -0.046802543, -0.14791425, -0.1390472, -0.1098524, -0.06986965, -0.08352...
1       [0.024382535, 0.25160155, -0.024762768, 0.100544535, -0.010385396, -0.26745123, 0.18688157, 0.44781923, -0.04938387, -0.3099036, -0.0603982, -0.22056091, -0.04846102, 0.041037083, -0.23096684, -0....
2       [-0.018117689, 0.20719163, 0.044322316, 0.1688867, 0.012457495, -0.16936843, 0.16158861, 0.46234274, 0.08859041, -0.21335109, -0.0075374176, -0.2565826, -0.03214297, -0.010630794, -0.23230916, -0....
3       [-0.0019014559, 0.21200553, 0.09751465, 0.24989986, 0.01471922, -0.1394132, 0.15352592, 0.51932186, 0.17294608, -0.2925092, 0.025813807, -0.32426283, -0.011893869, 0.0036866614, -0.28635877, -0.14...
4       [-0.015462129, 0.20235561, 0.08510054, 0.21714187, 0.01317949, -0.12117477, 0.14385526, 0.47332337, 0.14552645, -0.3413699, 0.017219625, -0.30623388, -0.01703965, 0.01706913, -0.2932266, -0.205596...
                                                                                                         ...                                                                                                   
7915    [0.022453379, 0.28288853, -0.09890395, 0.058894854, 0.013710669, -0.32903978, 0.2001462, 0.5610122, -0.052980352, -0.10128624, -0.03332875, -0.18287724, -0.06995111, -0.033491235, -0.15537234, -0....
7916    [-0.04356046, 0.26580676, 0.014817175, 0.15720543, 0.017327765, -0.23366682, 0.21374162, 0.5346311, -0.03390181, -0.28856093, -0.044030506, -0.29821107, -0.067398444, -0.027010804, -0.27448153, -0...
7917    [-0.007181555, 0.20744532, 0.09596292, 0.23133264, 0.016990153, -0.13202165, 0.16151449, 0.49149823, 0.1458246, -0.32394308, 0.006624317, -0.31506667, -0.019960253, 0.011937884, -0.3034088, -0.186...
7918    [0.02189662, 0.19855899, -0.0058776466, 0.0800388, -0.014078564, -0.23228738, 0.19161195, 0.36337614, -0.05397648, -0.22542967, -0.06918414, -0.17093, -0.064835064, 0.03306597, -0.19574681, -0.226...
7919    [0.0025054594, 0.23159103, -0.06815143, 0.05670796, 0.0110767055, -0.26300567, 0.19058871, 0.47291398, -0.032810073, -0.0492524, -0.019850904, -0.15020522, -0.07303989, -0.03259499, -0.13381958, -...
Name: cleaned_tweets, Length: 7920, dtype: object

In [ ]:
type(tweets_temp)

pandas.core.series.Series

In [ ]:
len(tweets_temp)

7920

In [ ]:
embedding_size = 300
tweets_vec = np.ones((len(tweets_temp), embedding_size))* np.nan
for i in range(len(tweets_temp)):
  tweets_vec[i,:] = tweets_temp.iloc[i]

tweets_vec.shape

(7920, 300)

In [ ]:
df = pd.DataFrame(tweets_vec)
df['y'] = data['label']
df.dropna(how='any',axis=0, inplace=True)
df.head()

0         1         2         3         4         5         6  \
0  0.090380  0.300299 -0.139539  0.033820  0.053803 -0.414673  0.295321   
1  0.023365  0.249643 -0.024401  0.110037  0.000661 -0.278919  0.208298   
2 -0.016571  0.191699  0.042235  0.173644  0.018948 -0.152452  0.177798   
3 -0.005488  0.189290  0.085831  0.250972  0.018788 -0.123707  0.166668   
4 -0.029072  0.189240  0.076711  0.231088  0.012588 -0.112229  0.166159   

          7         8         9  ...       291       292       293       294  \
0  0.620351 -0.148753  0.121360  ...  0.260073  0.144053  0.121084  0.271363   
1  0.491244 -0.066445 -0.296319  ...  0.302968  0.188638  0.002051  0.268969   
2  0.494155  0.108448 -0.179774  ...  0.268178  0.185048  0.093964  0.299161   
3  0.556737  0.204221 -0.261584  ...  0.323619  0.242160  0.130766  0.395307   
4  0.520098  0.178019 -0.301154  ...  0.315688  0.229096  0.098502  0.354207   

        295       296       297       298       299  y  
0  0.284538  0.105909 -0.215865  0.176172 -0.012357  0  
1  0.293374 -0.039792 -0.262925  0.133127 -0.167241  0  
2  0.264506 -0.001402 -0.131094  0.080488 -0.132619  0  
3  0.288522 -0.024782 -0.130478  0.064725 -0.171666  0  
4  0.302608 -0.036689 -0.135348  0.059794 -0.187018  1  

[5 rows x 301 columns]

In [ ]:
df.shape

(7920, 301)

In [ ]:
X_word_emb = df.drop('y',axis=1)
y = df['y']
X_word_emb.shape

(7920, 300)

In [ ]:
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_validate, cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
lr1 = LogisticRegression(class_weight='balanced',solver='liblinear',penalty='l1',C=0.4, random_state=42)
pipe = Pipeline([('SC', StandardScaler()),('LR',lr1)])

results = cross_validate(pipe, X_word_emb, y, cv=kfold, scoring='accuracy',return_train_score=True)
print(np.round(results['train_score'].mean()*100,2),np.round(results['train_score'].std()*100,2))

print(np.round(results['test_score'].mean()*100,2),np.round(results['test_score'].std()*100,2))



85.4 0.17
85.1 0.62


In [ ]:
X = data['cleaned_tweets']
y = data['label']

cv = CountVectorizer(min_df=5, max_features=300)

lr1 = LogisticRegression(class_weight='balanced',solver='liblinear',penalty='l1', C=0.4)
cv_pipe = Pipeline([('CV',cv),('LR',lr1)])

results = cross_validate(cv_pipe, X, y, cv=kfold, scoring='accuracy', return_train_score=True)


print(np.round(results['train_score'].mean()*100, 2), np.round(results['train_score'].std()*100,2))

print(np.round(results['test_score'].mean()*100, 2), np.round(results['test_score'].std()*100, 2))


88.95 0.07
87.75 1.01


In [ ]:
cv_pipe.fit(X,y)


Pipeline(steps=[('CV', CountVectorizer(max_features=300, min_df=5)),
                ('LR',
                 LogisticRegression(C=0.4, class_weight='balanced',
                                    penalty='l1', solver='liblinear'))])

In [ ]:
text = 'what worst service apple provided the worst '
pred = cv_pipe.predict([text])
pred

array([1])

array([0])

In [ ]:
X[:10]

0                                                                                                fingerprint pregnancy test android apps beautiful cute health igers iphoneonly iphonesia iphone
1                                                                                                           finally a transparant silicon case thanks to my uncle yay sony xperia s sonyexperias
2                                                                                                        we love this would you go talk makememories unplug relax iphone smartphone wifi connect
3                                                                                                                     i am wired i know i am george i wa made that way iphone cute daventry home
4                                                                         what amazing service apple will not even talk to me about a question i have unless i pay them for their stupid support
5                                                                                                                              iphone software update fucked up my phone big time stupid iphones
6                                                                                                                                          happy for u instapic instadaily u sony xperia xperiaz
7    new type c charger cable uk bay amazon etsy new year rob cross toby young evemun mcmafia taylor spectre newyear starting recipe technology samsunggalaxys iphonex pic twitter com pjiwq wtc
8                                                                                                   bout to go shopping again listening to music iphone justme music likeforlike followforfollow
9                                                                                                             photo fun selfie pool water sony camera picoftheday sun instagood boy cute outdoor
Name: cleaned_tweets, dtype: object

In [ ]:
y[:10]

0    0
1    0
2    0
3    0
4    1
5    1
6    0
7    0
8    0
9    0
Name: label, dtype: int64

In [ ]:
cv.fit_transform(X)
len(cv.vocabulary_)

300

In [ ]:
from gensim.models import keyedvectors
from gensim.scripts.glove2word2vec import glove2word2vec

In [ ]:
glove_input_file = '/content/drive/MyDrive/Sentiment_analysis_tweets/Data/glove.6B.300d.txt'

word2vec_output_file = 'word2vec.txt'

glove2word2vec(glove_input_file, word2vec_output_file)

<ipython-input-96-307231af9e31>:5: DeprecationWarning: Call to deprecated `glove2word2vec` (KeyedVectors.load_word2vec_format(.., binary=False, no_header=True) loads GLoVE text vectors.).
  glove2word2vec(glove_input_file, word2vec_output_file)


(400000, 300)

In [ ]:
filename = 'word2vec.txt'
model = keyedvectors.load_word2vec_format(filename, binary=False)

In [ ]:
model.get_vector('analytics')

array([-0.40548  ,  0.39364  ,  0.24022  ,  0.34127  ,  0.055648 ,
       -0.10803  ,  0.039164 ,  0.18937  , -0.45127  , -0.27871  ,
       -0.015266 ,  0.24798  ,  0.55061  ,  0.30861  ,  0.40948  ,
        0.73204  , -0.84074  , -0.48876  ,  0.32483  , -0.066804 ,
        0.016564 ,  0.24511  ,  0.83183  , -0.19639  ,  0.15246  ,
       -0.44795  , -0.0045132,  0.2346   , -0.44788  ,  0.30936  ,
       -0.37975  , -0.46415  ,  0.29201  ,  0.37153  , -0.20317  ,
        0.48227  ,  0.1073   , -0.0090965,  0.13635  , -0.65572  ,
       -0.19058  ,  0.18992  ,  0.09691  ,  1.09     , -0.44633  ,
       -0.49196  , -0.41965  ,  0.38035  , -0.43453  ,  0.31438  ,
       -0.26122  , -0.12057  ,  0.14399  , -0.89227  , -0.48884  ,
       -0.3605   , -0.53584  ,  0.27098  , -1.0588   , -0.52464  ,
        0.74812  , -0.62477  , -0.063618 , -0.44858  ,  0.24187  ,
        0.48308  ,  0.11666  , -0.030135 ,  0.16437  , -0.021701 ,
       -0.51816  ,  0.86906  , -0.20867  , -0.82157  , -0.5499

In [ ]:
model.get_vector('analytics')

array([-0.40548  ,  0.39364  ,  0.24022  ,  0.34127  ,  0.055648 ,
       -0.10803  ,  0.039164 ,  0.18937  , -0.45127  , -0.27871  ,
       -0.015266 ,  0.24798  ,  0.55061  ,  0.30861  ,  0.40948  ,
        0.73204  , -0.84074  , -0.48876  ,  0.32483  , -0.066804 ,
        0.016564 ,  0.24511  ,  0.83183  , -0.19639  ,  0.15246  ,
       -0.44795  , -0.0045132,  0.2346   , -0.44788  ,  0.30936  ,
       -0.37975  , -0.46415  ,  0.29201  ,  0.37153  , -0.20317  ,
        0.48227  ,  0.1073   , -0.0090965,  0.13635  , -0.65572  ,
       -0.19058  ,  0.18992  ,  0.09691  ,  1.09     , -0.44633  ,
       -0.49196  , -0.41965  ,  0.38035  , -0.43453  ,  0.31438  ,
       -0.26122  , -0.12057  ,  0.14399  , -0.89227  , -0.48884  ,
       -0.3605   , -0.53584  ,  0.27098  , -1.0588   , -0.52464  ,
        0.74812  , -0.62477  , -0.063618 , -0.44858  ,  0.24187  ,
        0.48308  ,  0.11666  , -0.030135 ,  0.16437  , -0.021701 ,
       -0.51816  ,  0.86906  , -0.20867  , -0.82157  , -0.5499